### ISSUE TITLE
How to resolve this error while building app project

### ISSUE THREAD

**Issue by anil-manjappa** [rkonovalov/jfilter#23]
setWebApplicationContext in com.jfilter.components.FilterProvider required a bean of type 'org.springframework.web.context.WebApplicationContext' that could not be found

**Comment by rkonovalov** [comment]
Which version of Spring Boot or Spring are you using?

**Comment by anil-manjappa** [comment]
2.3.0.RELEASE

**Comment by rkonovalov** [comment]
Please checkout next sample project: https://github.com/rkonovalov/jfilter-samples

And open in browser next url:
https://localhost:8080/swagger-ui.html

This project based on Swagger therefore you can run requests directly in browser
If browser prompts error with certificate, just press to "Proceed or visit site" button and Swagger main page should to open
It happens because sample project uses mock unsigned SSL certificate(SSL certificate required if you plan to ran it on Google Cloud or AWS)
