### ISSUE TITLE
SpringBoot support

### ISSUE THREAD

**Issue by ZoidbergVA** [rkonovalov/jfilter#3]
Hello @rkonovalov . I found your project and it was just what i needed for the project that i'm currently working on. Unfortunately you project does not work with spring boot, so i took a look at the source code, and the changes that need to be done to make it compatible are fairly minimal. The only issue i have now is that i have some tests that are failing and i can't seem to figure them out. Are you planning on supporting spring boot yourself or should i make a pull request and we can figure out the tests together?

**Comment by rkonovalov** [comment]
Hello @ZoidbergVA 
Thank you for interesting. I have tested JFilter module with Spring Boot 2.1.0.RELEASE version.
Maybe your issue is related with different version or other dependencies in your project. 
Anyway, I have added jfilter-spring-boot repository for test. Link: https://github.com/rkonovalov/jfilter-spring-boot
Could you please run tests in MainControllerTest. It should be passed without errors.

**Comment by ZoidbergVA** [comment]
Hello @rkonovalov. I tried your test repository and indeed the tests seem ok. Perhaps you are correct that the issue is a combination of dependencies. I will list here all the issues that i had in my project, and i will also try to make a repository to show them, but that will take a few days. 

I'm using spring boot version 2.0.0.RELEASE. 

Issues:
1) Cannot subclass final class com.jfilter.components.FileWatcher - this was solved by simply making the class not final. 

2) Is not really an issue with your project, more like weird spring boot behavior, but because of the @ComponentScan annotation, my path get's messed up and other dependencies do not get picked up / initialized correctly. - this was solved by putting @ComponentScan on EnableJsonFilter.

3) This is 2 issues caused by the same thing. Firstly @JsonFormat was ignored and i had an issue with LocalDate, LocalTime. LocalDateTime being serialized as objects instead of strings. - this was solved by autowiring the ObjectMapper in FilterJsonConverter / FilterXmlConverter and then in ConverterMapper in setIgnoreModifier instead of overwriting the SerializerFactory i got the SerializerFactory allready on the mapper and just added the SerializerModifier. 

4) I'm using springfox for an autogenerated swagger documentation and FilterRegister was ( i think ) overwriting some configurations. - this was solved by simply removing FilterRegister. 

I will leave another reply in a few days with a sample repository as well, to show all these issues.

**Comment by rkonovalov** [comment]
Hello @ZoidbergVA 
Thank you for details. Bellow comments regarding your issues:

1) I have removed final keyword and created Case #4 

2) After some tests I have found that you can try to use ComponentScans annotation instead of ComponentScan. As example

Instead of using: 
@ComponentScan({"com.jfilter.components", "com.your-project...."})

You can use:
@ComponentScans(value = {@ComponentScan({"com.jfilter", "com.jfilter.components"}),
@ComponentScan({"com.your-project...."})})

It could help to eliminate issue with weird spring boot behavior. But, I have decided on your advice to move ComponentScan anntation in EnableJsonFilter annotation and created Case #5 

3) I need more time to fix this issue. Maybe you can make repository with this issue.

4) FilterRegister using for adding FilterJsonConverter and FilterXmlConverter in Spring Converters list.
Without this component JFilter will be useless. And if this issue is critical for you, I also need repository with issue, for find a way how we can fix it.

**Comment by AdrianViman** [comment]
Hello @rkonovalov. 
I'm glad you were able to solve issues 1 and 2. 

Regarding issues 3 and 4, i'm going to try and make a repository tomorrow, but if you have any questions i can answer no problem. 

For case 3, you create a new ObjectMapper. I'm not sure in a non - spring-boot environment how this affects things, but in a spring-boot environment there already is a ObjectMapper bean created. I think it's best if you just autowire it and just return the autowired one. This way, in a spring-boot environment the one that is automatically created will be used, and in a non - spring-boot environment you just have to declare a bean of that type. This adds a bit of extra work for people who use jfilter but it's not really a big deal. 

For case 4, i just added a Component annotation on FilterJsonConverter and FilterXmlConverter and they were picked up.

**Comment by rkonovalov** [comment]
Hello @AdrianViman 
I have added changes based on your suggestion for case 3.

For case 4 I need more details. I tried to add Component annotation but it didn't work for me.
I think it's not enough to just add Component annotation. Also need register FilterJsonConverter and FilterXmlConverter in HttpMessageConverter list what actually does FilterRegister class.

**Comment by ZoidbergVA** [comment]
Hello @rkonovalov . 

Sorry to be back so late. I created a repo (it's kind off messy, sorry about that) to show my issues. https://github.com/ZoidbergVA/json-ignore-issues

Issues 1 and 2 are solved with the latest changes from jfilter, issue 3 and are not. 

To see issue 3 in action, build the repo, start the app and in a browser open localhost:8080/api/users/1 and you will see that the LocalDateTime is serialized as an object. 

To see issue 4 in action, build the repo, start the app and in a browser open http://localhost:8080/api/swagger-ui.html 
and you will see basic login page and in logs this line: 
WARN 5888 --- [nio-8080-exec-1] o.s.w.s.PageNotFound : No mapping found for HTTP request with URI [/api/swagger-ui.html] in DispatcherServlet with name 'dispatcherServlet'
but if you remove EnableJsonFilter from AppConfig you will see that the page loads correctly. 

If you have any questions, please let me know, i'm here and wanting to help. Thanks for the support.

**Comment by rkonovalov** [comment]
Hello @ZoidbergVA 
I have released 1.0.10 version with fixed issues 3, 4 (I Hope :))
Also for fixing case 3 with incorrect date format please add next annotation: @JsonSerialize(using = LocalDateTimeSerializer.class)

As in example:
...
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm")
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    @ApiModelProperty
    private LocalDateTime localDateTime;
...
I haven't found a better solution yet.

**Comment by ZoidbergVA** [comment]
Hello @rkonovalov. 
I can confirm that case 3 and 4 are working now. For case 3, indeed i need to add the JsonSerialize, and while not ideal, it's not really a big problem. 
You can close the issue. Thanks for the support.

**Comment by rkonovalov** [comment]
Hello @ZoidbergVA 
I have released 1.0.13 version which should fix issue with LocalDateTime without using @JsonSerialize(using = LocalDateTimeSerializer.class) annotation
